version: '3.7'
services:
  trino:
    hostname: trino
    image: 'trinodb/trino:351'
    ports:
      - '8085:8080'
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
    networks:
      - trino-network

  mariadb:
    hostname: mariadb
    image: mariadb:10.5.16
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network

  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - trino-network

  minio:
    hostname: mini
    image: 'minio/minio:latest'
    container_name: minioo
    ports:
      - '9001:9001'
      - '9000:9000'
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minio_username
      MINIO_ROOT_PASSWORD: minio_password
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge